### ISSUE TITLE
How to share a window with cmd when call open-wsl ?

### ISSUE THREAD

**Issue by HawkAaron** [mskyaxl/wsl-terminal#150]
Call open-wsl in cmd will launch a seperate window, but WSL stays in the same window.
How can we call open-wsl just like bash without launch a seperate window ?

**Comment by mskyaxl** [comment]
This is not possible because wsl-terminal starts wsl in mintty which has its own window. What you're looking for is maybe something like:

C:\Users\<user>\wsl-terminal\bin\mintty.exe  -i "C:\Users\<user>\wsl-terminal\open-wsl.exe" --rootfs=// --configdir "C:\Users\mosky\wsl-terminal\etc"  -t "        " cmd.exe

but then from cmd.exe you'll need to start somehow wsl using wslbridge
