### ISSUE TITLE
open-wsl.exe window closes immediately

### ISSUE THREAD

**Issue by SukkaW** [mskyaxl/wsl-terminal#163]
Currently I am using [Pengwin](https://github.com/WhitewaterFoundry/Pengwin) and the latest version of `wsl-terminal` on `WIndows 10 Enterprise Insider Preview Build 18945`.

I have read issues #36 and #63, and follow the debug steps in `bin` directory and I got:

```
./wslbridge.exe bash -c pwd
wslbridge error: failed to start backend process
note: backend error output: -35062: -c: line 0: unexpected EOF while looking for matching `''
-35062: -c: line 1: syntax error: unexpected end of file
```

`./mintty.exe -h error -e /bin/wslbridge -t bash` just give me a same error message.

What should I do to fix this?

**Comment by jason404** [comment]
I have this happening with wsltty, so I tried installing wsl-terminal and the same thing.

It must be due to the latest Windows Insider build, as this started just after it installed.

**Comment by SukkaW** [comment]
@jason404 I think I have located where the issue is https://github.com/microsoft/WSL/issues/4337

**Comment by sirredbeard** [comment]
You can temporarily edit your profile files to get access to your Pengwin system, but pengwin-setup will not work on WSL2.

We recommend setting your system up on WSL1, applying the workaround below, and then converting to WSL2. You will need to covert back to use pengwin-setup though.

See https://github.com/WhitewaterFoundry/Pengwin/issues/497.

Note there are other, unrelated bugs in WSL2 in Insider releases since 18945, in 18950 and 18956, that can cause serious problems.

For now we recommend build 18941 and testing WSL2 in Hyper-V or non-production hardware only.

**Comment by SukkaW** [comment]
@sirredbeard 

Even if I convert back to WSL1, the issue still appears.

**Comment by es50678** [comment]
I have the same issue after fresh installing `0.8.13`, using WSL 2 with ubuntu 18.04

**Comment by TimoMeijer** [comment]
Same issue with Ubuntu on WSL1

**Comment by weibolu** [comment]
Same issue on Windows build 19025, how to solve it?

**Comment by sirredbeard** [comment]
Please follow-up with the Pengwin team.

**Comment by ParadoxZW** [comment]
The same issue happens to me, but my wsl is just debian, not Pengwin. And the wsl version is v1.
How can I solve it.
